### ISSUE TITLE
Create new Fields type

### ISSUE THREAD

**Issue by diegonakamashi** [Vizir/carnivaljs#2]
Create fields for textbox, number, currency, boolean .. etc

**Comment by jkiyo** [comment]
Done.

Directives:
- carnivalTextField for type: "text"
- carnivalNumberField for type: "number"
- carnivalCurrencyField for type: "currency"
- carnivalBooleanField for type: "boolean"
- carnivalDateField for type: "date"
- carnivalEnumField for type: "enum"
- carnivalFileField for type: "file"
- carnivalStringField for type: "string"
- carnivalWysiwygField for type: "wysiwyg"
